name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Frame.png
    - assets/ellipse.png
    - assets/google.png
    - assets/facebook.png
    - assets/Icon.png
    - assets/rect.png
    - assets/line.png
    - assets/mountain.png
    - assets/video.png
    - assets/fork.png
    - assets/fries.png
    


